apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-gateway
  namespace: cde-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-api
  namespace: cde-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-ledger
  namespace: cde-ledger
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-ledger
