apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: demo
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/part-of: kind-playground
data:
  APP_ENV: playground
  LOG_LEVEL: info
  ECHO_TEXT: "demo-api from ConfigMap"
  WELCOME: "kind playground"
