apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
    app.kubernetes.io/name: demo-app
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
