apiVersion: v1
kind: Namespace
metadata:
  name: cde-gateway
  labels:
    pci.northstar.example/scope: cde
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    goldilocks.fairwinds.com/enabled: "true"
