apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    pci.northstar.example/scope: connected-to
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
