apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: platform
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      labels:
        workload: platform
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: {{ .Values.platform.expireAfter | quote }}
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            {{- range .Values.instanceCategories }}
            - {{ . | quote }}
            {{- end }}
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
  limits:
    cpu: {{ .Values.platform.limits.cpu | quote }}
    memory: {{ .Values.platform.limits.memory | quote }}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: {{ .Values.platform.consolidateAfter | quote }}
