apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  role: {{ .Values.nodeRoleName | quote }}
  amiSelectorTerms:
    - alias: {{ .Values.amiAlias | quote }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: {{ .Values.volumeSize | quote }}
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: {{ .Values.clusterName | quote }}
    Name: {{ printf "%s-karpenter" .Values.clusterName | quote }}
